---
sabnzbd:
  image: kohlby/sabnzbd
  hostname: sabnzbd
  domainname: kohlby.fr
  volumes:
    - /opt/ejson/keys:/opt/ejson/keys:ro
    - /mnt/docker/sabnzbd:/data
    - /mnt/media:/media
  log_driver: "syslog"
  log_opt:
    syslog-tag: compose.sabnzbd
  cap_add:
    - SYS_ADMIN
  user: root
sickrage:
  image: kohlby/sickrage
  hostname: sickrage
  domainname: kohlby.fr
  volumes:
    - /opt/ejson/keys:/opt/ejson/keys:ro
    - /mnt/docker/sickrage:/data
    - /mnt/media:/media
  log_driver: "syslog"
  log_opt:
    syslog-tag: compose.sickrage
  cap_add:
    - SYS_ADMIN
  user: root
couchpotato:
  image: kohlby/couchpotato
  hostname: couchpotato
  domainname: kohlby.fr
  volumes:
    - /opt/ejson/keys:/opt/ejson/keys:ro
    - /mnt/docker/couchpotato:/data
    - /mnt/media:/media
  log_driver: "syslog"
  log_opt:
    syslog-tag: compose.couchpotato
  cap_add:
    - SYS_ADMIN
  user: root
plex:
  image: kohlby/plex
  net: host
  hostname: plex
  domainname: kohlby.fr
  volumes:
    - /opt/ejson/keys:/opt/ejson/keys:ro
    - /mnt/docker/plex:/data
    - /mnt/media:/media
  log_driver: "syslog"
  log_opt:
    syslog-tag: compose.plex
  cap_add:
    - SYS_ADMIN
  user: root
nginx:
  image: kohlby/nginx
  hostname: www
  domainname: kohlby.fr
  log_driver: "syslog"
  log_opt:
    syslog-tag: compose.nginx
  user: root
  links:
    - sabnzbd
    - sickrage
    - couchpotato
  ports:
    - 80:80
timemachine:
  image: kohlby/timemachine
  hostname: timemachine
  domainname: kohlby.fr
  log_driver: "syslog"
  log_opt:
    syslog-tag: compose.timemachine
  volumes:
    - /opt/ejson/keys:/opt/ejson/keys:ro
    - /mnt/timemachine_adrien:/timemachine/adrien
    - /mnt/timemachine_coline:/timemachine/coline
  cap_add:
    # shr exec
    - SYS_ADMIN
    # netatalk
    - SYS_RESOURCE
  user: root
  ports:
    - 548:548
